# Generated by Django 2.1.5 on 2020-04-02 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20200402_1414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name_plural': 'professors'},
        ),
    ]
