# Generated by Django 2.1.5 on 2020-04-02 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_auto_20200402_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='picture',
            field=models.ImageField(blank=True, upload_to='media/profile_images'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='createdby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='media/profile_images'),
        ),
    ]
